CrudCoreReview/Models/ContactoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace CrudCoreReview.Models
{
    public class ContactoModel
    {
        public int idContacto { get; set; }

        [Required(ErrorMessage ="El campo Nombre es obligatorio")]
        public string nomContacto { get; set; }

        [Required(ErrorMessage = "El campo Telefono es obligatorio")]
        public string telContacto { get; set; }

        [Required(ErrorMessage = "El campo Correo es obligatorio")]
        public string correoContacto { get; set; }
    }
}

CrudCoreReview/Models/ErrorViewModel.cs
using System;

namespace CrudCoreReview.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudCoreReview/Controllers/HomeController.cs
using CrudCoreReview.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CrudCoreReview.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrudCoreReview/Controllers/MantenedorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CrudCoreReview.Datos;
using CrudCoreReview.Models;

namespace CrudCoreReview.Controllers
{
    public class MantenedorController : Controller
    {

        ContactoDatos _ContactoDatos = new ContactoDatos();

        public IActionResult List()
        {
            //retorna lista de contactos
            var oList = _ContactoDatos.List();
            return View(oList);
        }

        public IActionResult Save()
        {
            //metodo solo devuelve la lista
            return View();
        }
        [HttpPost]
        public IActionResult Save(ContactoModel oContacto)
        {
            //metodo recibe el objeto para guardarlo en bd

            if (!ModelState.IsValid)
            {
                return View();
            }


            var response = _ContactoDatos.save(oContacto);

            if (response)
                return RedirectToAction("List");
            else                
                return View();
        }

        public IActionResult Update(int idContacto)
        {
            //metodo solo devuelve la lista
            var oContacto = _ContactoDatos.Get(idContacto);
            return View(oContacto);
        }

        [HttpPost]
        public IActionResult Update(ContactoModel oContacto)
        {
            //metodo recibe el objeto para guardarlo en bd

            if (!ModelState.IsValid)
            {
                return View();
            }


            var response = _ContactoDatos.update(oContacto);

            if (response)
                return RedirectToAction("List");
            else
                return View();
        }


        public IActionResult Delete(int idContacto)
        {
            //metodo solo devuelve la lista
            var oContacto = _ContactoDatos.Get(idContacto);
            return View(oContacto);
        }

        [HttpPost]
        public IActionResult Delete(ContactoModel oContacto)
        {
            //metodo recibe el objeto para guardarlo en bd

            var response = _ContactoDatos.delete(oContacto.idContacto);

            if (response)
                return RedirectToAction("List");
            else
                return View();
        }
    }
}

CrudCoreReview/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CrudCoreReview/Views/Mantenedor/Delete.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Eliminar contacto
    </div>
    <div class="card-body">
        <form asp-action="Delete" asp-controller="Mantenedor" method="post">
            <input asp-for="idContacto" type="hidden" class="form-control">

            <div class="alert alert-danger" role="alert">
                ¿ Desea eliminar el contacto : @Html.DisplayTextFor(m=>m.nomContacto) ?
            </div>
            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a asp-action="List" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

CrudCoreReview/Views/Mantenedor/List.cshtml
@model List<ContactoModel>
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h4>Lista contacto</h4>
    </div>
    <div class="card-body">
        <a asp-action="Save" asp-controller="Mantenedor" class="btn btn-success"><i class="bi bi-plus-circle"></i> Crear nuevo</a>
        <hr />
        <table class="table table-dark table-striped">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Telefono</th>
                    <th scope="col">Correo</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
            {
                <tr>
                    <td>@item.idContacto</td>
                    <td>@item.nomContacto</td>
                    <td>@item.telContacto</td>
                    <td>@item.correoContacto</td>
                    <td>
                        <a asp-action="Update" asp-controller="Mantenedor" class="btn btn-primary btn-sb" asp-route-idContacto="@item.idContacto"><i class="bi bi-pencil-fill"></i> Editar</a>
                        <a asp-action="Delete" asp-controller="Mantenedor" class="btn btn-danger btn-sb" asp-route-idContacto="@item.idContacto"><i class="bi bi-trash3-fill"></i> Eliminar</a>
                    </td>

                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

CrudCoreReview/Views/Mantenedor/Save.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Save";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h4>Crear contacto</h4>
    </div>
    <div class="card-body">
        <form asp-action="Save" asp-controller="Mantenedor" method="post">
            <div class="mb-3">
                <label class="form-label">Nombre de Contacto</label>
                <input asp-for="nomContacto" type="text" class="form-control" >  
                <span asp-validation-for="nomContacto" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Telefono de Contacto</label>
                <input asp-for="telContacto" type="text" class="form-control">
                <span asp-validation-for="telContacto" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Correo de Contacto</label>
                <input asp-for="correoContacto" type="text" class="form-control">
                <span asp-validation-for="correoContacto" class="text-danger"></span>
            </div>            
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="List" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

CrudCoreReview/Views/Mantenedor/Update.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h4>Editar contacto</h4>
    </div>
    <div class="card-body">
        <form asp-action="Update" asp-controller="Mantenedor" method="post">
            <input asp-for="idContacto" type="hidden" class="form-control">
            <div class="mb-3">
                <label class="form-label">Nombre de Contacto</label>
                <input asp-for="nomContacto" type="text" class="form-control">
                <span asp-validation-for="nomContacto" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Telefono de Contacto</label>
                <input asp-for="telContacto" type="text" class="form-control">
                <span asp-validation-for="telContacto" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Correo de Contacto</label>
                <input asp-for="correoContacto" type="text" class="form-control">
                <span asp-validation-for="correoContacto" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="List" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

CrudCoreReview/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudCoreReview</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrudCoreReview</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Developed by Angelo Contreras Requena - <a href="https://github.com/AngeloContrera5" target="_blank">Github</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>